### 
# Test API routes
GET {{$dotenv HEROKU_ENDPOINT}}/api/hello-world

###
# Test webhook routes
POST {{$dotenv HEROKU_ENDPOINT}}/webhook/hello-world
Content-Type: application/json

{
  "hello": "world"
}

###
# Testing hosted webhook
POST {{$dotenv HEROKU_ENDPOINT}}/webhook/recharge/order-created
Content-Type: application/json

< ./order.json

###
# Add Webhook
POST https://api.rechargeapps.com/webhooks
Content-Type: application/json
X-Recharge-Access-Token: {{$dotenv RECHARGE_ACCESS_TOKEN}}
Accept: application/json

{
	"address": "{{$dotenv HEROKU_ENDPOINT}}/webhook/recharge/order-created",
	"topic": "order/created"
}

###
# List webhooks
GET https://api.rechargeapps.com/webhooks
Content-Type: application/json
X-Recharge-Access-Token: {{$dotenv RECHARGE_ACCESS_TOKEN}}
Accept: application/json

###
# List webhooks
DELETE https://api.rechargeapps.com/webhooks/1174398
Content-Type: application/json
X-Recharge-Access-Token: {{$dotenv RECHARGE_ACCESS_TOKEN}}
Accept: application/json

